name: 4. Build Loop
run-name: Build Loop (${{ github.ref_name }})
on:
  workflow_dispatch:
  schedule:
    - cron: "33 7 * * 0"

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  UPSTREAM_REPO: LoopKit/LoopWorkspace
  UPSTREAM_BRANCH: ${{ github.ref_name }}
  TARGET_BRANCH: ${{ github.ref_name }}

jobs:
  check_status:
    runs-on: ubuntu-latest
    name: Check status to decide whether to build
    permissions:
      contents: write
    outputs:
      NEW_COMMITS: ${{ steps.sync.outputs.has_new_commits }}
      IS_SECOND_IN_MONTH: ${{ steps.date-check.outputs.is_second_instance }}

    steps:
      - name: Access
        id: workflow-permission
        run: |
          set -o pipefail
          GH_PAT_CLASSIC_PATTERN='^ghp_[a-zA-Z0-9]{36}$'
          GH_PAT_FINE_GRAINED_PATTERN='^github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}$'
          
          if [ -z "$GH_PAT" ]; then
            failed=true
            echo "::error::The GH_PAT secret is unset or empty."
          else
            if [[ $GH_PAT =~ $GH_PAT_CLASSIC_PATTERN ]] || [[ $GH_PAT =~ $GH_PAT_FINE_GRAINED_PATTERN ]]; then
              echo "has_permission=true" >> $GITHUB_OUTPUT
            fi
          fi
          if [ $failed ]; then exit 2; fi

      - name: Checkout target repo
        if: steps.workflow-permission.outputs.has_permission == 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Sync upstream changes
        if: steps.workflow-permission.outputs.has_permission == 'true' && github.repository_owner != 'LoopKit'
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: ${{ env.TARGET_BRANCH }}
          target_repo_token: ${{ secrets.GH_PAT }}
          upstream_sync_branch: ${{ env.UPSTREAM_BRANCH }}
          upstream_sync_repo: ${{ env.UPSTREAM_REPO }}

      - name: Check if this is the second time this day-of-week happens this month
        id: date-check
        run: |
          DAY_OF_MONTH=$(date +%-d)
          WEEK_OF_MONTH=$(( ($(date +%-d) - 1) / 7 + 1 ))
          if [[ $WEEK_OF_MONTH -eq 2 ]]; then
            echo "is_second_instance=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_second_instance=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build
    needs: [check_status]
    runs-on: macos-15
    permissions:
      contents: write
    if: |
      github.event_name == 'workflow_dispatch' ||
      (needs.check_status.outputs.IS_SECOND_IN_MONTH == 'true') ||
      (needs.check_status.outputs.NEW_COMMITS == 'true')
    steps:
      - name: Select Xcode version
        run: "sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer"

      - name: Checkout Repo for building
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          ref: ${{ env.TARGET_BRANCH }}

      - name: Customize Loop
        run: |
          # Apply local patches if they exist
          if [ -d "./patches" ] && [ "$(ls -A ./patches)" ]; then
            git apply ./patches/* --allow-empty -v --whitespace=fix
          fi

          # Apply LNL Script Customizations
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/loopandlearn/lnl-scripts/main/CustomizationSelect.sh)" \
          future_carbs_4h \
          override_sens \
          now_line \
          lnl_icon \
          watch_title

      - name: Patch Match Tables
        run: |
          TABLE_PRINTER_PATH=$(ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir')/match/lib/match/table_printer.rb
          if [ -f "$TABLE_PRINTER_PATH" ]; then
            sed -i "" "/puts(Terminal::Table.new(params))/d" "$TABLE_PRINTER_PATH"
          fi

      - name: Install Project Dependencies
        run: bundle install

      - name: Sync clock
        run: sudo sntp -sS time.windows.com

      - name: Fastlane Build & Archive
        run: bundle exec fastlane build_loop
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Fastlane upload to TestFlight
        run: bundle exec fastlane release
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            artifacts
            buildlog
